/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_11 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] sum;
  
  reg [15:0] xb;
  
  always @* begin
    xb = {5'h10{alufn[0+0-:1]}} ^ b;
    sum = a + b;
    n = sum[15+0-:1];
    v = (a[15+0-:1] & xb[15+0-:1] & !sum[15+0-:1]) | (!a[15+0-:1] & !xb[15+0-:1] & sum[15+0-:1]);
    z = ~(|sum);
    out = sum;
  end
endmodule
