/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiplier_14 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] out,
    output reg div_by_zero
  );
  
  
  
  always @* begin
    div_by_zero = 1'h0;
    
    case (alufn[0+1-:2])
      2'h0: begin
        out = a * b;
      end
      2'h1: begin
        if (b == 1'h0) begin
          div_by_zero = 1'h1;
          out = 16'h0000;
        end else begin
          out = a / b;
        end
      end
      2'h2: begin
        if (b == 1'h0) begin
          div_by_zero = 1'h1;
          out = 16'h0000;
        end else begin
          out = a - (a / b) * a;
        end
      end
      default: begin
        out = 16'h0000;
      end
    endcase
  end
endmodule
