/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rom_multiplier2_8 (
    input [4:0] test_case,
    output reg [15:0] a,
    output reg [15:0] b,
    output reg [5:0] alufn,
    output reg [15:0] exp_out,
    output reg exp_z,
    output reg exp_v,
    output reg exp_n,
    output reg exp_e,
    output reg [4:0] num_cases
  );
  
  
  
  localparam TEST_A = 96'h000000050005fff60003fffb;
  
  localparam TEST_B = 96'h0005000000020002000a000a;
  
  localparam ALUFN = 36'h186186186;
  
  localparam EXP_OUT = 96'h0000000000010000fffdfffb;
  
  localparam EXP_ZVN = 18'h08049;
  
  localparam EXP_E = 6'h10;
  
  always @* begin
    num_cases = 5'h06;
    a = TEST_A[(test_case)*16+15-:16];
    b = TEST_B[(test_case)*16+15-:16];
    alufn = ALUFN[(test_case)*6+5-:6];
    exp_out = EXP_OUT[(test_case)*16+15-:16];
    exp_e = EXP_E[(test_case)*1+0-:1];
    exp_z = EXP_ZVN[(test_case)*3+2+0-:1];
    exp_v = EXP_ZVN[(test_case)*3+1+0-:1];
    exp_n = EXP_ZVN[(test_case)*3+0+0-:1];
  end
endmodule
