/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rom_boolean_5 (
    input [4:0] test_case,
    output reg [15:0] a,
    output reg [15:0] b,
    output reg [5:0] alufn,
    output reg [15:0] exp_out,
    output reg exp_z,
    output reg exp_v,
    output reg exp_n,
    output reg [4:0] num_cases
  );
  
  
  
  localparam AND = 6'h18;
  
  localparam OR = 6'h1e;
  
  localparam XOR = 6'h16;
  
  localparam A = 6'h1a;
  
  localparam NAND = 6'h17;
  
  localparam NOR = 6'h11;
  
  localparam XNOR = 6'h19;
  
  localparam B = 6'h1c;
  
  localparam TEST_A = 128'hff00ff00ff00ff00ff00ff00ff00ff00;
  
  localparam TEST_B = 128'hf0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0;
  
  localparam ALUFN = 48'h61e59a5d165c;
  
  localparam EXP_OUT = 128'hf000fff00ff0ff0000ff000ff00ff0f0;
  
  localparam EXP_ZVN = 24'h000000;
  
  always @* begin
    num_cases = 5'h08;
    a = TEST_A[(test_case)*16+15-:16];
    b = TEST_B[(test_case)*16+15-:16];
    alufn = ALUFN[(test_case)*6+5-:6];
    exp_out = EXP_OUT[(test_case)*16+15-:16];
    exp_z = EXP_ZVN[(test_case)*3+2+0-:1];
    exp_v = EXP_ZVN[(test_case)*3+1+0-:1];
    exp_n = EXP_ZVN[(test_case)*3+0+0-:1];
  end
endmodule
