/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rom_multiplier1_7 (
    input [4:0] test_case,
    output reg [15:0] a,
    output reg [15:0] b,
    output reg [5:0] alufn,
    output reg [15:0] exp_out,
    output reg exp_z,
    output reg exp_v,
    output reg exp_n,
    output reg exp_e,
    output reg [4:0] num_cases
  );
  
  
  
  localparam TEST_A = 208'h0000fffb0001000101f401f4fe0c000000050005fff60003fffb;
  
  localparam TEST_B = 208'h00050000000afff601f4fe0cfe0c0005000000020002000a000a;
  
  localparam ALUFN = 78'h04104104105145145145;
  
  localparam EXP_OUT = 208'h00000000000afff6d0902f70d090000000000002fffb00000000;
  
  localparam EXP_ZVN = 39'h1244108049;
  
  localparam EXP_E = 13'h0010;
  
  always @* begin
    num_cases = 5'h0d;
    a = TEST_A[(test_case)*16+15-:16];
    b = TEST_B[(test_case)*16+15-:16];
    alufn = ALUFN[(test_case)*6+5-:6];
    exp_out = EXP_OUT[(test_case)*16+15-:16];
    exp_e = EXP_E[(test_case)*1+0-:1];
    exp_z = EXP_ZVN[(test_case)*3+2+0-:1];
    exp_v = EXP_ZVN[(test_case)*3+1+0-:1];
    exp_n = EXP_ZVN[(test_case)*3+0+0-:1];
  end
endmodule
