/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rom_comparator_6 (
    input [4:0] test_case,
    output reg [15:0] a,
    output reg [15:0] b,
    output reg [5:0] alufn,
    output reg [15:0] exp_out,
    output reg exp_z,
    output reg exp_v,
    output reg exp_n,
    output reg [4:0] num_cases
  );
  
  
  
  localparam CMPEQ = 6'h33;
  
  localparam CMPLT = 6'h35;
  
  localparam CMPLE = 6'h37;
  
  localparam TEST_A = 256'h0237fc8b001e810c029e00d2fe0c0078ff9c029e00007ef40361000aff9c029e;
  
  localparam TEST_B = 256'hff2efe34001e012c02a6ff2efe0c0078006402a60000fed4fe0c000a006402a6;
  
  localparam ALUFN = 96'hdf7df7df3cf3cf3cf5d75d75;
  
  localparam EXP_OUT = 256'h0000000100010001000100000001000100000000000100000000000000010001;
  
  localparam EXP_ZVN = 48'h062040063109;
  
  always @* begin
    num_cases = 5'h10;
    a = TEST_A[(test_case)*16+15-:16];
    b = TEST_B[(test_case)*16+15-:16];
    alufn = ALUFN[(test_case)*6+5-:6];
    exp_out = EXP_OUT[(test_case)*16+15-:16];
    exp_z = EXP_ZVN[(test_case)*3+2+0-:1];
    exp_v = EXP_ZVN[(test_case)*3+1+0-:1];
    exp_n = EXP_ZVN[(test_case)*3+0+0-:1];
  end
endmodule
