/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rom_shifter_9 (
    input [4:0] test_case,
    output reg [15:0] a,
    output reg [15:0] b,
    output reg [5:0] alufn,
    output reg [15:0] exp_out,
    output reg exp_z,
    output reg exp_v,
    output reg exp_n,
    output reg [4:0] num_cases
  );
  
  
  
  localparam SHL = 6'h20;
  
  localparam SHR = 6'h21;
  
  localparam SRA = 6'h23;
  
  localparam TEST_A = 96'h000a02370361fff6fe38fd5a;
  
  localparam TEST_B = 96'h000200030004000200030004;
  
  localparam ALUFN = 36'h8218e0863;
  
  localparam EXP_ZVN = 18'h00049;
  
  localparam EXP_OUT = 96'h0028006c0023ffd81fabffe3;
  
  always @* begin
    num_cases = 5'h05;
    a = TEST_A[(test_case)*16+15-:16];
    b = TEST_B[(test_case)*16+15-:16];
    alufn = ALUFN[(test_case)*6+5-:6];
    exp_out = EXP_OUT[(test_case)*16+15-:16];
    exp_z = EXP_ZVN[(test_case)*3+2+0-:1];
    exp_v = EXP_ZVN[(test_case)*3+1+0-:1];
    exp_n = EXP_ZVN[(test_case)*3+0+0-:1];
  end
endmodule
